abstract class  ServiceProviderHomePageStates{}
class InitialState extends ServiceProviderHomePageStates{}
class ServiceProviderHomePageLoading extends ServiceProviderHomePageStates {}
class ServiceProviderHomePageSuccess extends ServiceProviderHomePageStates{}
class ServiceProviderHomePageEmpty extends ServiceProviderHomePageStates{}